baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Dorf-Troedel'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[params]
site_logo = "/logo.png"
cover_dimming_class = "fancy-bg"
background_color_class = "fancy-bg"
custom_css = ["custom.css"]
